db.driver=org.postgresql.Driver
db.url=${PROD_DB_URL}
db.username=${PROD_DB_USERNAME}
db.password=${PROD_DB_PASSWORD}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false
hibernate.format_sql=false
