db.driver=org.postgresql.Driver
db.url=${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/GYM?currentSchema=gymcrm_local}
db.username=${LOCAL_DB_USERNAME:postgres}
db.password=${LOCAL_DB_PASSWORD:admin123}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=true
