spring.profiles.default=local

server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jackson.serialization.write-dates-as-timestamps=false

security.default.role=ADMIN

db.url=jdbc:postgresql://localhost:5432/GYM?currentSchema=gymcrm
db.username=postgres
db.password=admin123
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.info.enabled=true
management.prometheus.metrics.export.enabled=true

info.app.name=GYM CRM System
info.app.description=Gym CRM REST API
info.app.version=1.0-SNAPSHOT
