db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/GYM?currentSchema=gymcrm_local
db.username=postgres
db.password=admin123

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=true

security.default.role=ADMIN
