db.driver=org.h2.Driver
db.url=jdbc:h2:file:./data/GYM;MODE=MySQL;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE
db.username=sa
db.password=

hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=false
hibernate.format_sql=true

security.default.role=ADMIN
